/* ==========================================================================
   gen-sri.mjs — emit Subresource-Integrity digests for every CDN-servable asset.

   Consumers loading 8-BIT NES from a CDN can pin *bytes*, not just a version:

     <link rel="stylesheet" integrity="sha384-…" crossorigin="anonymous"
           href="https://cdn.jsdelivr.net/npm/8bit-nes@X.Y.Z/all.min.css">

   Emits (repo root):
     • sri.json — { version, algorithm, cdn, files: { path: "sha384-…" } }

   Fonts are listed too. A font pulled in by `url()` inside the CSS can't carry
   an `integrity` attribute, so those digests are for *verification* — checking a
   vendored/air-gapped mirror really holds the published bytes.

   Runs after the esbuild steps (it hashes their output). Zero deps,
   deterministic (no clock/random) so CI can diff it. Run: pnpm gen:sri
   ========================================================================== */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8"));

const ALGO = "sha384"; // the SRI sweet spot: stronger than sha256, universally supported

/* Every asset a browser can fetch straight off the CDN. Order is fixed, not
   globbed, so the output is stable and a new file is a deliberate edit. */
const ASSETS = [
  // recommended entry points (one request each)
  "all.min.css",
  "elements.min.js",
  "icons.min.js",
  // unminified / granular equivalents
  "all.css",
  "tokens.css",
  "base.css",
  "components.css",
  "elements.js",
  "icons.js",
  // machine-readable docs (RAG consumers fetch these over HTTP too)
  "components.json",
  "llms.txt",
  "llms-full.txt",
  // fonts — referenced by url() from the CSS, so same-version URLs must match
  "fonts/nes-sans-var.woff2",
  "fonts/nes-mono-400.woff2",
  "fonts/nes-mono-700.woff2",
];

const digest = (rel) =>
  `${ALGO}-${createHash(ALGO)
    .update(readFileSync(join(ROOT, rel)))
    .digest("base64")}`;

const files = {};
for (const rel of ASSETS) files[rel] = digest(rel);

const out = {
  $comment:
    "Generated by scripts/gen-sri.mjs — do not edit by hand. Digests are of the published bytes for this exact version; a version bump changes every value.",
  name: pkg.name,
  version: pkg.version,
  algorithm: ALGO,
  cdn: `https://cdn.jsdelivr.net/npm/${pkg.name}@${pkg.version}`,
  files,
};

writeFileSync(join(ROOT, "sri.json"), `${JSON.stringify(out, null, 2)}\n`);

console.log(
  `gen-sri: wrote sri.json — ${Object.keys(files).length} assets, ${ALGO}, v${pkg.version}.`,
);
